export const TypeAction = {
  changeCity: 'changeCity',
  selectSortingVariant: 'selectSortingVariant',
  activateCard: 'activateCard',
  loadOffers: 'loadOffers',
  loadOffer: 'loadOffer',
  loadNear: 'loadNear',
  loadComments: 'loadComments',
  addUser: 'addUser',
  setIsOffersLoaded: 'setIsOffersLoaded',
  fetchOffers: 'fetchOffers',
  fetchOffer: 'fetchOffer',
  checkAuth: 'checkAuth',
  authorization: 'authorization',
  redirect: 'redirect',
  redirectToRoute: 'redirectToRoute',
  postComment: 'postComment',
  setOfferLoading: 'setOfferLoading',
  setAuthorizationStatus: 'setAuthorizationStatus',
  setEmail: 'setEmail'
} as const;
